### ISSUE TITLE
Mystifier modifier key inoperable if pressed after drag start

### ISSUE THREAD

**Issue by dhemery** [xdy/xdy-pf2e-workbench#200]
In order to use the selected modifier key (Ctrl or Alt) to mystify a token, it seems as if I must press the modifier key before I begin dragging the actor off the sidebar. If I press the mouse button, then drag even slightly before pressing the modifier key, the token is not mystified.

Is that the intended behavior?

PF2e Workbench: 2.40.2
OS: macOS Monterey 12.3.1
Browser: Chrome Version 100.0.4896.60 (Official Build) (arm64)

**Comment by xdy** [comment]
That is a bit strange, the code should just care that the key is pressed as the token is released (technically, a *very* short time after the token is released).
Unfortunately I cannot debug it (when I do it doesn't behave the same as when not debugging), and I feel the issue is minor enough (given that there is a workaround, pressing the modifier key early enough) that it's not worth digging deeper into.
So,  while not quite the intended behavior, I feel it's close enough.

**Comment by dhemery** [comment]
On Discord, Tikael said: "It's how the handlers normally work if they are set up on drag instead of on drop."

If that suggests an easy fix, please consider it.

On a mac the workaround is awkward with the Crtl key. I can't press the Crtl key before pressing the mouse button, because that raises the context menu. So I have to press the mouse button, then (without moving the mouse even slightly) press the Crtl key, then drag.

That's especially awkward in the middle of a combat, when the game is moving very quickly and I have a whole lot of other things to attend to.
