### ISSUE TITLE
Summoners get the reminder that their Eidolon is unable to attack.

### ISSUE THREAD

**Issue by sorrythatuserbla** [xdy/xdy-pf2e-workbench#348]
Summoners always get the reminder that their Eidolon is unable to attack due to the shared health pool and the Eidolon having 0 HP.

**Comment by xdy** [comment]
Oh, right. In my game we avoided that by simply not having a shared health pool. :)
Or, rather, they do, but we gave the eidolon a 'feat' with a name like 'summoner hit points' with an effect like this (change value as appropriate)
```{"key":"FlatModifier","selector":"hp","value":148,"type":"untyped"}```
and the summoner updates the hit points of both. The original reason was that the summoner almost died because everyone forgot he took the damage while the eidolon's state never changed. :)

Anyway, I'll try to fix this next time I do something on the workbench, until then, the above is a half-decent workaround.

**Comment by sorrythatuserbla** [comment]
Thanks for the tipp!
I guess there is not way to really link them (yet)? Anyway, gonna do what you wrote. Big thanks

**Comment by xdy** [comment]
Unfortunately no. Once the PF2e Companion Compendia module gets absorbed into the system I expect they'll link the summoner and eidolon kind of like familiars are linked now.

**Comment by xdy** [comment]
Handled in Workbench 3.36.0
