### ISSUE TITLE
feature request: ability to de-mystify

### ISSUE THREAD

**Issue by ditzer252** [xdy/xdy-pf2e-workbench#4]
Great module!  Thank you.  Would it be possible to bake in an easy way to de-mystify an NPC, like after a PC does recall knowledge?  Thanks again!

**Comment by xdy** [comment]
Yeah, that feature is coming. I just need to figure out how I want to do it.

Current todo in the code:
```
//TODO Add a way to revert the name change from the sheet. (Hover over the name gives a context menu? Or inject a button on the sheet title bar? Maybe just a function that can be called from a macro?)
```

A 'demystify' button on the token sheet title bar would probably be the most usable. (Or maybe use an icon in addition to/instead of the text? An eye perhaps? [fa fas-eye-slash](https://fontawesome.com/v5.15/icons/eye-slash) for mystified and [fa fa-eye](https://fontawesome.com/v5.15/icons/eye) for demystified?)
But, that would also take up space on the title bar, which can get somewhat crowded if you - like me - use way too many modules...
![image](https://user-images.githubusercontent.com/246024/142937280-5a1cdbf3-cf60-40f0-9aae-04dc76c980dd.png)
Oh, and, of course, I'd need to figure out how to actually do it. :)

**Comment by ditzer252** [comment]
Awesome.  A mystify/de-mystify button on the character sheet or in the HUD would be super useful.
Right now I'm using the following macro to de-mystify a selected token.

let updates = canvas.tokens.controlled.filter(t => t.name !== t.actor.data.name).map(t => { return {_id: t.id, name: t.actor.data.name}});
canvas.tokens.updateMany(updates);

**Comment by xdy** [comment]
I've now added a mystify/unmystify button on the HUD in 1.5.0, though only for one token at a time.
Having the HUD affect all selected tokens would be useful though, so I won't close this issue just yet.

**Comment by ditzer252** [comment]
It's excellent. Thank you!
