### ISSUE TITLE
[Request] Add Support for Token Action Hud for Skill Actions

### ISSUE THREAD

**Issue by Vaizt** [xdy/xdy-pf2e-workbench#483]
It would be nice to be able to access these actions without having to open the character sheet. My players and I have been looking forward to when this might happen as it improves the flow of the game just a bit.

**Comment by apoapostolov** [comment]
Token Action HUD allows for compendiums of macros to be assigned to any category. I do what you want in my own world by creating a compendium and then a macro for every action, and assigning images to these macros, and then assigning it to Actions section as a custom subsection.

This page, a commission for a macro I am funding that will do the same thing but as a macro with UI, contains the macro lines for each separate macro. 
https://apoapostolov.notion.site/PF2-Basic-Actions-Macro-1255adc12ecf44e881e6cd87941f7858

**Comment by Vaizt** [comment]
I already use the pre-existing action compendium for this. However, a tailored version based off of the actions available to that player would be a nice quality of life feature.

**Comment by apoapostolov** [comment]
Might be possible with a future update of TAH because one of the devs plan to make every section and subsection fully customizable and if there's even opportunity for an API for one mod to register options in TAH, it would come after that.

**Comment by xdy** [comment]
I'm unlikely to add support for Token Action Hud as I do not use it myself (though I would accept a PR that does this).
The macro apoastolov mentions above is good enough I'm currently recommending that to my players rather than turning on Skill Actions. (It needs a few more things, like Escape, but it's *very* close to being a one stop shop.)
So, I'm closing this issue.
