### ISSUE TITLE
Bug: Inline templates and rolls no longer work. 

### ISSUE THREAD

**Issue by apoapostolov** [xdy/xdy-pf2e-workbench#486]
WB 4.7.0, PF2 latest, FVTT 10. Tested with culrpit. 

Since update to 4.7.0, when creating new posts, inline templates and checks/saving throws no longer post by clicking on the chat icon, or can be rolled by clicking on the inline label.  Dice rolls such as [[/r xdx]] work as normal. Old posts created while Workbench is deactivated (such as during culprit testing) work as normal even with Workbench. 

![image](https://user-images.githubusercontent.com/4083812/196210827-46c0abf8-fc2a-4e85-8210-d43c761edda1.png)

**Comment by xdy** [comment]
I'm not able to reproduce this. I tried locally in a test world with just the workbench, and in my main game world on the forge with all kinds of modules installed. For both tests I used a hell hound, and it always worked to click the damage, template and save buttons, as gm and player.
I *did* get an error in the console when using this, which I've fixed in 4.7.1 (just pushed, should be out in a few minutes).
Please let me know if you get the same error on that version

**Comment by apoapostolov** [comment]
Tested in 4.7.1, the problem still remains.

**Comment by apoapostolov** [comment]
Seems like this bug affects only creatures from Beginner's Box, so I am now leaning towards this being not a Workbench problem.

Hell Hound (BB) from Beginner's Box has this problem. Hell Hound from Bestiary, as well as other monsters I tested (Young White Dragon, etc.) don't have this problem. 

So this can be closed.

**Comment by sorrythatuserbla** [comment]
Be sure to deactivate this feature.
![image](https://user-images.githubusercontent.com/78597675/197975234-11346e82-783c-45f7-ba3e-8f7d5861904c.png)
