### ISSUE TITLE
LANG FILES

### ISSUE THREAD

**Issue by TaleSale** [xdy/xdy-pf2e-workbench#554]
Add strings to language files to translate action strings and recall information.

**Comment by Far2Casual** [comment]
Seconded, I've seen the action strings are hardcoded in English, we're up for translation (french community)

**Comment by rectulo** [comment]
I support the Dwim message !

**Comment by xdy** [comment]
I assume you mean the recall knowledge button on npcs?
For those my problem is that I don't know how to get the english skill name, which I need to be able to build the string @Check[type:${skill}|dc:${dcs[i]}|traits:secret,action:recall-knowledge]"
In english it works to get the skill and use that, but, when I test in german I see that I instead get the translated one. E.g. instead of religion I get religionskunde.
Do you know if there is a way to get the english skill name from the translated one?

**Comment by xdy** [comment]
Of course, now that I think about it, why *do* I get the german skill name from data-skill? It seems the name of the css class has also been translated, which is probably not right. E.g.:
![image](https://user-images.githubusercontent.com/246024/210138456-d6391d42-d531-470d-8060-fc7d7efd2c58.png)
I'll check if it's the same in french.

**Comment by xdy** [comment]
(Removed previous comment, was barking up the wrong tree.)
In french, this is the information I have available to build the button from, which does not include the english name.
![image](https://user-images.githubusercontent.com/246024/210138843-3d590cd9-5990-4ae5-aee5-8255ad110f55.png)

**Comment by xdy** [comment]
If you meant missing translated strings in some other place, please send a screen shot so I can see where it is missing.

**Comment by Far2Casual** [comment]
Hello, at least for myself I was talking about the action name labels in the Basic Action Macros screen: 
![image](https://user-images.githubusercontent.com/63196064/210185481-13cfe1a9-65cb-4d9f-94f6-9fa9a935593a.png)

**Comment by xdy** [comment]
I *think* I've added localization for everything except the Customizable macros where I can't add it as I don't know how they'll be used, so closing this issue.
