### ISSUE TITLE
Basic action macro missing Disable Device

### ISSUE THREAD

**Issue by xanstin** [xdy/xdy-pf2e-workbench#624]
There is not button for disable device. Pick a lock thievery sub action is there however.

**Comment by xdy** [comment]
Closing this issue as Disable Device is excluded due to there not existing a macro for that action in the system, or in Symon's collection of macros. Without such a macro there is nothing for Basic Action Macros to call. (Support for Disable Device *is* included in the Skill Actions feature that puts relevant actions on the character sheet. One of these days I really should get around to consolidating these two features. Alas, that day is not today...)
