### ISSUE TITLE
[BUG] Breath weapon reminder on recharge abilities without the word "breath" in them does not work

### ISSUE THREAD

**Issue by xavien12** [xdy/xdy-pf2e-workbench#778]
The Breath weapon reminder does not work. If you are in an encounter and use an ability that has a recharge of 1d4 or 1d6 rounds and click on it, the only thing that happens is that a secret roll is put into chat. This roll is a typical damage roll. It used to be that an effect would be placed on the creature to show how many rounds there were left until it is up again.

**Comment by xdy** [comment]
Hmm. Seems to work for me (tested with an Adult Bronze Dragon on the latest system version).
The feature requires the creature ability to have text matching this regex: "\\[\\[\\/(b|)r 1d([4|6])( .*?)((rounds|recharge|cooldown)).*?]]" (this is visible if you edit the creature and then click the pen button in the text editor)
This means that it must start with [[ immediately followed by either /r or /br; a space; 1d4 or 1d6; then the following text must contain any of the words rounds, recharge or cooldown; and finally it may have more text before the final ]] that ends the inline roll.
I.e. the Adult Bronze Dragon has this, which works:
```The dragon can't use Breath Weapon again for [[/br 1d4 #Recharge Breath Weapon]]{1d4 rounds}.```
If a creature uses some format, like say '/r 1d6 #Recharg]] that wouldn't work (in this case because recharge was spelled wrong.)

What creature did you use?

**Comment by xavien12** [comment]
I originally had that problem with the jungle drake. I assume its because its breath weapon is called spit venom. I tested it with an adult bronze dragon and other drakes and it works. It seems like it only does the recharge if the action has breath in it. The regex of the jungle drake has the matching breath weapon text [[/br 1d6 #Recharge Spit Venom]]{1d6 rounds}. I renamed spit venom to poison breath and it does the recharge. Its weird because the regex still says Spit Venom so its specifically the name of the ability that gets checked.
