### ISSUE TITLE
Falling Unconscious shouldn't drop shields

### ISSUE THREAD

**Issue by ChaseDonnally** [xdy/xdy-pf2e-workbench#794]
Shields are strapped to you by RAW and should not be dropped when falling unconscious

**Comment by ChaseDonnally** [comment]
Ok actually, I might be wrong about this.

The section on [Wielding Items](https://2e.aonprd.com/Rules.aspx?ID=194) says "detaching a shield or item strapped to you" takes 1 action but the only shield that calls out being strapped is the Buckler. It's possible this line really just means "detach an item strapped to you, which includes a subset of shield"

**Comment by roguedevjake** [comment]
> Ok actually, I might be wrong about this.
> 
> The section on [Wielding Items](https://2e.aonprd.com/Rules.aspx?ID=194) says "detaching a shield or item strapped to you" takes 1 action but the only shield that calls out being strapped is the Buckler. It's possible this line really just means "detach an item strapped to you, which includes a subset of shield"

All shields are logically strapped to you, they cannot function otherwise.

Bucklers are separate and specifically mention strapped because you don't hold them at all (which is dumb, but the D&D buckler is more like an archer's shield rather than an actual buckler) 

> 

[Image: the back of a targe (round shield)](https://scottishtargesbydouglas.files.wordpress.com/2021/08/dsc_0457.jpg)

[Image: the back of a kite shield](https://www.shutterstock.com/image-photo/back-side-medieval-kite-shield-visible-1166288137)

[Image: the back of a roman tower shield](https://qph.cf2.quoracdn.net/main-qimg-0c903b8a0cb76cf32b4a212a6eca79f0-lq)

**Comment by roguedevjake** [comment]
> 

[Image: the back of a shield](https://scottishtargesbydouglas.files.wordpress.com/2021/08/dsc_0457.jpg)
